Repository sycamore-rs/sycamore, pull requests merged in 2021-11, with the labels that each got.

#269 Builder API
  Cargo.toml
  examples/hello-builder/Cargo.toml
  examples/hello-builder/index.html
  examples/hello-builder/src/main.rs
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore/Cargo.toml
  packages/sycamore/src/builder/agnostic/mod.rs
  packages/sycamore/src/builder/html.rs
  packages/sycamore/src/builder/mod.rs
  packages/sycamore/src/generic_node.rs
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/ssr_node.rs
  packages/sycamore/src/lib.rs
  website/sitemap_index.xml
Labels: enhancement, A-builder

#293 Fix contexts in Keyed and Indexed
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore-reactive/src/iter.rs
  packages/sycamore-reactive/src/lib.rs
  packages/sycamore/src/builder/agnostic/mod.rs
  website/sitemap_index.xml
Labels: bug, A-context

#274 Add `IS_BROWSER` constant to `GenericNode`
  packages/sycamore-macro/src/component/mod.rs
  packages/sycamore-macro/src/template/component.rs
  packages/sycamore-macro/tests/template/component-fail.rs
  packages/sycamore-macro/tests/template/component-pass.rs
  packages/sycamore/src/builder/agnostic/mod.rs
  packages/sycamore/src/generic_node.rs
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/ssr_node.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/src/portal.rs
  website/src/main.rs
Labels: BREAKING CHANGE, ergonomics, A-SSR

#297 Make `GenericNode` generic over the event type
  packages/sycamore-router/src/router.rs
  packages/sycamore/src/builder/agnostic/mod.rs
  packages/sycamore/src/generic_node.rs
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/ssr_node.rs
Labels: enhancement, BREAKING CHANGE

#300 Rename `StateHandle` to `ReadSignal`
  docs/next/advanced/routing.md
  docs/next/basics/components.md
  examples/components/src/main.rs
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore-reactive/src/iter.rs
  packages/sycamore-reactive/src/signal.rs
  packages/sycamore-router/src/router.rs
  packages/sycamore/src/builder/agnostic/mod.rs
  packages/sycamore/src/flow.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/src/view.rs
  website/src/main.rs
Labels: enhancement, BREAKING CHANGE

#301 Autocomplete should not be boolean attribute
  packages/sycamore-macro/src/view/attributes.rs
Labels: bug

#240 Hydrate
  .github/workflows/test.yml
  Cargo.toml
  docs/next/advanced/ssr.md
  examples/counter/src/main.rs
  examples/hydrate/Cargo.toml
  examples/hydrate/index.html
  examples/hydrate/src/main.rs
  packages/sycamore-macro/Cargo.toml
  packages/sycamore-macro/src/component/mod.rs
  packages/sycamore-macro/src/view/attributes.rs
  packages/sycamore-macro/src/view/component.rs
  packages/sycamore-macro/src/view/element.rs
  packages/sycamore/Cargo.toml
  packages/sycamore/src/builder/agnostic/mod.rs
  packages/sycamore/src/component.rs
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/hydrate_dom.rs
  packages/sycamore/src/generic_node/mod.rs
  packages/sycamore/src/generic_node/ssr_node.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/src/utils/hydrate/mod.rs
  packages/sycamore/src/utils/hydrate/web.rs
  packages/sycamore/src/utils/mod.rs
  packages/sycamore/src/utils/render.rs
  packages/sycamore/tests/ssr/main.rs
  packages/sycamore/tests/web/hydrate.rs
  packages/sycamore/tests/web/main.rs
  website/index.css
  website/package-lock.json
  website/sitemap_index.xml
Labels: enhancement, BREAKING CHANGE, A-SSR

#304 Fix parenthesizing of expressions in `view!` interpolation syntax
  packages/sycamore-macro/Cargo.toml
  packages/sycamore-macro/src/view/element.rs
  packages/sycamore-macro/tests/view/element-pass.rs
Labels: bug, A-macro, A-view

#306 Add `#[track_caller]` for `use_context`
  packages/sycamore-reactive/src/context.rs
Labels: ergonomics, A-context

#307 Better debugging for `ReactiveScope`s
  packages/sycamore-macro/src/component/mod.rs
  packages/sycamore-macro/src/lib.rs
  packages/sycamore-reactive/src/context.rs
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore-reactive/src/lib.rs
  packages/sycamore/src/context.rs
Labels: A-reactivity, ergonomics

#309 Deprecate create_root in favor of create_scope
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore-reactive/src/lib.rs
  packages/sycamore/src/context.rs
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/hydrate_dom.rs
  packages/sycamore/src/generic_node/ssr_node.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/tests/web/cleanup.rs
  packages/sycamore/tests/web/portal.rs
Labels: A-reactivity
