Repository sycamore-rs/sycamore, pull requests merged in 2021-03, with the labels that each got.

#16 Receive Event in callback (Part 1)
  Cargo.toml
  README.md
  examples/components/src/main.rs
  examples/counter/src/main.rs
  examples/hello/Cargo.toml
  examples/hello/index.html
  examples/hello/src/main.rs
  maple-core-macro/src/attributes.rs
  maple-core-macro/src/element.rs
  maple-core-macro/src/lib.rs
  maple-core-macro/tests/ui/component-fail.stderr
  maple-core-macro/tests/ui/element-fail.rs
  maple-core-macro/tests/ui/element-fail.stderr
  maple-core-macro/tests/ui/element-pass.rs
  maple-core/Cargo.toml
  maple-core/src/internal.rs
  maple-core/src/lib.rs
Labels: enhancement

#20 Replace functions with Signal type
  examples/components/src/main.rs
  examples/counter/src/main.rs
  examples/hello/src/main.rs
  maple-core/src/lib.rs
  maple-core/src/reactive.rs
Labels: enhancement

#29 Refactor effect dependency tracking
  .github/workflows/build_docs.yml
  .github/workflows/rust.yml
  maple-core/src/reactive.rs
Labels: bug, reactivity

#34 Add cloned! macro
  README.md
  examples/components/src/main.rs
  examples/counter/src/main.rs
  examples/hello/src/main.rs
  maple-core/src/lib.rs
  maple-core/src/macros.rs
  maple-core/src/reactive.rs
Labels: enhancement, ergonomics, macro

#37 Create effects within a reactivity root
  docs/src/main.rs
  examples/components/src/main.rs
  examples/counter/src/main.rs
  examples/hello/src/main.rs
  maple-core/Cargo.toml
  maple-core/benches/reactivity.rs
  maple-core/src/lib.rs
  maple-core/src/macros.rs
  maple-core/src/reactive.rs
  maple-core/src/reactive/effect.rs
  maple-core/src/reactive/signal.rs
Labels: bug, reactivity

#36 Control flow in template!
  examples/hello/src/main.rs
  maple-core-macro/src/children.rs
  maple-core-macro/src/lib.rs
  maple-core/Cargo.toml
  maple-core/src/internal.rs
  maple-core/src/lib.rs
Labels: enhancement, macro

#41 Nested templates
  README.md
  docs/src/header.rs
  docs/src/usage.rs
  examples/components/src/main.rs
  examples/counter/src/main.rs
  examples/hello/src/main.rs
  maple-core-macro/src/children.rs
  maple-core-macro/src/element.rs
  maple-core-macro/src/lib.rs
  maple-core-macro/src/text.rs
  maple-core/src/internal.rs
  maple-core/src/lib.rs
  maple-core/src/reactive/effect.rs
  maple-core/src/reactive/signal.rs
  maple-core/src/render.rs
Labels: BREAKING CHANGE, macro

#24 Component lifecycle
  maple-core/src/lib.rs
  maple-core/src/reactive.rs
  maple-core/src/reactive/effect.rs
Labels: components, enhancement

#49 Iteration
  docs/Cargo.toml
  examples/hello/Cargo.toml
  examples/todomvc/Cargo.toml
  examples/todomvc/src/main.rs
  maple-core/Cargo.toml
  maple-core/src/lib.rs
  maple-core/src/reactive.rs
  maple-core/src/reactive/effect.rs
  maple-core/src/reactive/signal.rs
  maple-core/src/reactive/signal_vec.rs
  maple-core/src/render.rs
  scripts/netlify-build
Labels: reactivity

#51 Iteration on `Signal<Vec>` and integration tests
  .github/workflows/test.yml
  examples/todomvc/src/main.rs
  maple-core/Cargo.toml
  maple-core/src/flow.rs
  maple-core/src/lib.rs
  maple-core/src/reactive/signal_vec.rs
  maple-core/tests/integration.rs
Labels: enhancement, reactivity

#54 Fix reactive bindings inside Indexed and Keyed children
  examples/todomvc/src/main.rs
  maple-core/src/flow.rs
  maple-core/src/reactive.rs
  maple-core/src/reactive/effect.rs
  maple-core/src/reactive/signal.rs
  maple-core/tests/integration.rs
Labels: bug, reactivity

#57 Node refs
  examples/todomvc/src/main.rs
  maple-core-macro/src/attributes.rs
  maple-core-macro/src/element.rs
  maple-core/src/internal.rs
  maple-core/src/lib.rs
  maple-core/src/noderef.rs
  maple-core/tests/integration.rs
Labels: enhancement, macro

#60 Complete TodoMVC spec conforming implementation
  examples/todomvc/Cargo.toml
  examples/todomvc/index.html
  examples/todomvc/src/copyright.rs
  examples/todomvc/src/footer.rs
  examples/todomvc/src/header.rs
  examples/todomvc/src/item.rs
  examples/todomvc/src/list.rs
  examples/todomvc/src/main.rs
  maple-core-macro/src/component.rs
  maple-core-macro/src/lib.rs
  maple-core-macro/tests/ui/component-fail.stderr
  maple-core/Cargo.toml
  maple-core/src/flow.rs
  maple-core/src/lib.rs
  maple-core/src/reactive/effect.rs
  maple-core/src/reactive/signal.rs
  maple-core/tests/integration.rs
Labels: bug, examples

#73 Fix Keyed iteration
  maple-core/src/flow.rs
  maple-core/tests/integration/keyed.rs
  maple-core/tests/integration/main.rs
  maple-core/tests/integration/non_keyed.rs
Labels: bug
