Repository sycamore-rs/sycamore, pull requests merged in 2022-02, with the labels that each got.

#342 Add blog post about the new reactive primitives
  docs/posts/new-reactive-primitives.md
  website/sitemap_index.xml
  website/src/news_index.rs
Labels: website

#344 Make dispose an unsafe fn
  packages/sycamore-reactive/examples/nested-scopes.rs
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore-reactive/src/iter.rs
  packages/sycamore-reactive/src/lib.rs
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/hydrate_dom.rs
  packages/sycamore/tests/web/cleanup.rs
Labels: bug, soundness

#346 Add unit test for Signal::split
  packages/sycamore-reactive/src/signal.rs
  packages/sycamore/tests/ssr/main.rs
Labels: test

#347 Refresh README.md and add example list
  README.md
  examples/README.md
Labels: documentation

#354 Type-checking and IDE completions for HTML tags
  packages/sycamore-macro/src/view/codegen.rs
  packages/sycamore-macro/tests/view/element-fail.rs
  packages/sycamore-macro/tests/view/element-fail.stderr
  packages/sycamore/src/component.rs
  packages/sycamore/src/html/mod.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/src/suspense.rs
Labels: A-macro, ergonomics

#355 Add workflow for monitoring performance
  .github/workflows/build_website.yml
  .github/workflows/build_website_prod.yml
  .github/workflows/js_framework_bench.yml
  Cargo.toml
  docs/Cargo.toml
  docs/src/lib.rs
  docs/src/main.rs
  examples/js-framework-benchmark/src/main.rs
  packages/sycamore-router-macro/Cargo.toml
  packages/sycamore-router/Cargo.toml
  packages/tools/bench-diff/Cargo.toml
  packages/tools/bench-diff/src/main.rs
  packages/tools/configure_bench.js
Labels: performance, ci

#356 Enable wasm-opt for js-framework-benchmark
  examples/js-framework-benchmark/index.html
  website/package.json
Labels: performance

#357 Call cleanup callbacks in map_keyed and map_indexed
  packages/sycamore-reactive/src/iter.rs
Labels: bug, A-reactivity, performance

#358 Use a SmallVec for ScopeArena
  packages/sycamore-reactive/Cargo.toml
  packages/sycamore-reactive/src/arena.rs
Labels: performance

#359 Remove unnecessary heap allocation in create_effect
  examples/js-framework-benchmark/src/main.rs
  packages/sycamore-reactive/src/context.rs
  packages/sycamore-reactive/src/effect.rs
  packages/sycamore-reactive/src/lib.rs
  packages/sycamore/src/view.rs
Labels: A-reactivity, performance

#360 Remove lexical and pass number directly to JS
  docs/src/main.rs
  packages/sycamore/Cargo.toml
  packages/sycamore/src/generic_node/dom_node.rs
  packages/sycamore/src/generic_node/mod.rs
  packages/sycamore/src/view.rs
  website/sitemap_index.xml
Labels: performance

#364 Create a new nested scope if `ctx` is used within a dyn fragment
  packages/sycamore-macro/src/view/codegen.rs
  packages/sycamore-macro/src/view/ir.rs
  packages/sycamore-macro/src/view/mod.rs
  packages/sycamore-reactive/src/context.rs
  packages/sycamore/src/generic_node/ssr_node.rs
  packages/sycamore/src/view.rs
  packages/sycamore/tests/ssr/main.rs
  website/Cargo.toml
Labels: bug, A-macro, A-view

#371 Update iteration.md
  docs/next/basics/iteration.md
Labels: documentation
