Repository sycamore-rs/sycamore, pull requests merged in 2023-10, with the labels that each got.

#629 Update README.md example with new reactivity system]
  README.md
Labels: A-docs

#630 Dont suggest wee-alloc in docs
  docs/next/advanced/optimize_wasm_size.md
Labels: A-docs

#631 Make batch affect both memos and effects
  packages/sycamore-reactive/src/effects.rs
  packages/sycamore-reactive/src/root.rs
Labels: C-bug, A-reactivity, performance

#632 Repace the `Memo` struct with `ReadSignal`
  examples/todomvc/src/main.rs
  packages/sycamore-core/src/view.rs
  packages/sycamore-reactive/src/iter.rs
  packages/sycamore-reactive/src/memos.rs
  packages/sycamore-reactive/src/signals.rs
  packages/sycamore-reactive/src/utils.rs
  packages/sycamore-router/src/router.rs
  packages/tools/bench/benches/reactivity.rs
Labels: C-enhancement, A-reactivity, BREAKING CHANGE

#637 Update components documentation for v0.9
  docs/next/basics/components.md
Labels: A-docs

#636 Add a CONTRIBUTING.md and remove old contributing docs
  CONTRIBUTING.md
  docs/next/contribute/architecture.md
  docs/next/contribute/development.md
  docs/next/sidebar.json
  website/sitemap_index.xml
Labels: A-docs, meta

#639 Fix panic about current not being a child of parent in clean_children
  packages/sycamore-core/src/render.rs
Labels: C-bug

#642 Re-export `wasm-bindgen`, `js-sys`, and event types from `web-sys`
  examples/js-framework-benchmark/Cargo.toml
  examples/todomvc/Cargo.toml
  packages/sycamore-web/src/lib.rs
Labels: C-enhancement, A-ergonomics

#643 Add missing docs and more doctests
  packages/sycamore-core/src/component.rs
  packages/sycamore-core/src/event.rs
  packages/sycamore-core/src/generic_node.rs
  packages/sycamore-core/src/lib.rs
  packages/sycamore-core/src/stable_id.rs
  packages/sycamore-futures/src/lib.rs
  packages/sycamore-macro/src/lib.rs
  packages/sycamore-reactive/src/effects.rs
  packages/sycamore-reactive/src/lib.rs
  packages/sycamore-reactive/src/node.rs
  packages/sycamore-reactive/src/signals.rs
  packages/sycamore-reactive/src/utils.rs
  packages/sycamore-router-macro/src/lib.rs
  packages/sycamore-web/src/lib.rs
Labels: A-docs
