Repository sycamore-rs/sycamore, pull requests merged in 2023-03, with the labels that each got.

#586 Add signal equivalent of `create_ref_unsafe`
  packages/sycamore-reactive/src/signal.rs
Labels: C-enhancement, A-reactivity

#552 Do not add values to the arena drop list if not necessary
  packages/sycamore-reactive/Cargo.toml
  packages/sycamore-reactive/src/arena.rs
Labels: performance

#594 Prepare v0.9.0-beta.1
  docs/next/advanced/routing.md
  docs/next/getting_started/installation.md
  packages/sycamore-core/Cargo.toml
  packages/sycamore-futures/Cargo.toml
  packages/sycamore-macro/Cargo.toml
  packages/sycamore-reactive/Cargo.toml
  packages/sycamore-router-macro/Cargo.toml
  packages/sycamore-router/Cargo.toml
  packages/sycamore-web/Cargo.toml
  packages/sycamore/Cargo.toml
  website/src/versions.rs
Labels: meta
