Repository sycamore-rs/sycamore, pull requests merged in 2024-09, with the labels that each got.

#681 Update some old docs
  docs/next/basics/view.md
  docs/next/getting_started/hello_world.md
Labels: A-docs

#682 Fix `set_fn` to not be silent
  packages/sycamore-reactive/src/signals.rs
Labels: C-bug, A-reactivity

#688 Make `ViewHtmlNode` methods use `Cow<'static, str>` instead of `&'static str`
  packages/sycamore-web/src/elements.rs
  packages/sycamore-web/src/node/dom.rs
  packages/sycamore-web/src/node/hydrate.rs
  packages/sycamore-web/src/node/mod.rs
  packages/sycamore-web/src/node/ssr.rs
Labels: BREAKING CHANGE

#690 Fix `NoHydrate` should render if not hydrating
  packages/sycamore-web/src/components.rs
Labels: C-bug, A-hydration

#691 Remove `nom` dependency and replace with hand written parser
  packages/sycamore-router-macro/Cargo.toml
  packages/sycamore-router-macro/src/parser.rs
  packages/sycamore-router-macro/src/route.rs
  packages/sycamore-router-macro/tests/router/router-fail.rs
  packages/sycamore-router-macro/tests/router/router-fail.stderr
Labels: C-enhancement, A-router

#693 Move `MaybeDyn` to new file and add some impls
  packages/sycamore-reactive/src/utils.rs
  packages/sycamore-web/src/lib.rs
  packages/sycamore-web/src/maybe_dyn.rs
  packages/sycamore-web/src/node/mod.rs
Labels: C-enhancement

#694 Reimplement attribute passthrough, without `attr:xyz`!
  examples/attributes-passthrough/src/main.rs
  packages/sycamore-macro/src/props.rs
  packages/sycamore-macro/src/view.rs
  packages/sycamore-macro/tests/view/component-fail.rs
  packages/sycamore-macro/tests/view/component-fail.stderr
  packages/sycamore-macro/tests/view/component-pass.rs
  packages/sycamore-macro/tests/view/element-fail.stderr
  packages/sycamore-macro/tests/view/element-pass.rs
  packages/sycamore-web/src/attributes.rs
  packages/sycamore-web/src/elements.rs
  packages/sycamore-web/src/lib.rs
  packages/sycamore-web/src/maybe_dyn.rs
  packages/sycamore-web/src/node/dom_node.rs
  packages/sycamore-web/src/node/hydrate_node.rs
  packages/sycamore-web/src/node/mod.rs
  packages/sycamore-web/src/node/ssr_node.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/tests/web/main.rs
  packages/sycamore/tests/web/reconcile.rs
Labels: C-enhancement

#695 Fix suspense rendering async shell during fallback
  packages/sycamore-web/Cargo.toml
  packages/sycamore-web/src/iter.rs
  packages/sycamore-web/src/lib.rs
  packages/sycamore-web/src/node/dom_node.rs
  packages/sycamore-web/src/node/ssr_render.rs
  packages/sycamore-web/src/portal.rs
  packages/sycamore-web/src/suspense.rs
  packages/sycamore-web/src/utils.rs
Labels: C-bug, A-async

#696 SSR Streaming
  Cargo.toml
  examples/http-request-builder/src/main.rs
  examples/http-request/src/main.rs
  examples/hydrate/index.html
  examples/hydrate/src/main.rs
  examples/ssr-streaming/Cargo.toml
  examples/ssr-streaming/Trunk.toml
  examples/ssr-streaming/index.html
  examples/ssr-streaming/src/app.rs
  examples/ssr-streaming/src/main.rs
  examples/ssr-streaming/src/server.rs
  examples/transitions/src/main.rs
  packages/sycamore-futures/src/lib.rs
  packages/sycamore-futures/src/suspense.rs
  packages/sycamore-reactive/src/root.rs
  packages/sycamore-web/Cargo.toml
  packages/sycamore-web/src/attributes.rs
  packages/sycamore-web/src/components.rs
  packages/sycamore-web/src/elements.rs
  packages/sycamore-web/src/lib.rs
  packages/sycamore-web/src/macros.rs
  packages/sycamore-web/src/node/dom_render.rs
  packages/sycamore-web/src/node/hydrate_node.rs
  packages/sycamore-web/src/node/mod.rs
  packages/sycamore-web/src/node/ssr_node.rs
  packages/sycamore-web/src/node/ssr_render.rs
  packages/sycamore-web/src/suspense.rs
  packages/sycamore-web/src/utils.rs
  packages/sycamore/src/lib.rs
  packages/sycamore/tests/web/hydrate.rs
  packages/sycamore/tests/web/indexed.rs
  packages/sycamore/tests/web/keyed.rs
Labels: C-enhancement, A-SSR

#697 Remove Gitpod
  .gitpod.Dockerfile
  .gitpod.yml
Labels: meta

#698 v0.9.0-beta.4
  Cargo.toml
  docs/next/advanced/routing.md
  docs/next/getting_started/installation.md
  packages/sycamore-core/Cargo.toml
  packages/sycamore-futures/Cargo.toml
  packages/sycamore-macro/Cargo.toml
  packages/sycamore-router/Cargo.toml
  packages/sycamore-web/Cargo.toml
  packages/sycamore/Cargo.toml
  website/src/versions.rs
Labels: meta

#700 Fix router on different pathname and hash triggers hard refresh
  packages/sycamore-router/src/router.rs
Labels: C-bug, A-router

#701 Fix suspense should create context in global scope
  packages/sycamore-futures/src/suspense.rs
Labels: C-bug, A-async

#707 Allow attribute names by using string literal
  docs/next/basics/view.md
  packages/sycamore-macro/src/view.rs
  packages/sycamore-macro/tests/view/element-pass.rs
  packages/sycamore-view-parser/src/ir.rs
  packages/sycamore-view-parser/src/parse.rs
Labels: C-enhancement
